permalink: /:year/:month/:day/:title/

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", ".bundle", "vendor"]
highlighter: rouge

# Site metadata
title: James Verbus
tagline:
default_og_image: /assets/images/jverbus_neutron_generator_outside_lux.jpg
author:
  name: James Verbus
  email: james.verbus@gmail.com
  github: jverbus
  twitter: JamesVerbus

url: https://jverbus.github.io
baseurl: ""

plugins: ["jekyll-sitemap"]
